# Vector and Matrices

For our purposes, we call a **vector** an ordered list of real numbers, e.g. 

     0.1 -0.5 3.2


The length of the list is the **dimension** of the vector. 

The i_th_ element in the list is sometimes called the i_th_ **component** (a.k.a. **coordinate**) of the vector. 

In Python, we use `numpy.array` to create a vector

In [4]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([3, 4, -1])
print(v1)
print(v2)

[1 2 3]
[ 3  4 -1]


One can access the components of a vector use indexing, just as for regular Python lists. 

In [5]:
print(v1[0])  # first element of v1
print(v2[1])  # second element of v2

1
4


## operations on vectors

Addition of two vectors

In [6]:
v1 + v2 

array([4, 6, 2])

Element-wise multiplication

In [7]:
v1 * v2

array([ 3,  8, -3])

multiplication by a scalar (real number)


In [8]:
3. * v1

array([3., 6., 9.])

### Inner product, dot product or scalar product

Given vectors of size `n`, one defines their inner product as the sum of the  products of the corresponding elements.

In [12]:
print(np.inner(v1, v2))
print(sum(v1 * v2))

8
8


In [ ]:
The norm of a vector is the square root of the

## Matrices

A **Matrix** is a list of vectors. If we represent these vectors side by side, the matrix is represented as a table *n*p$ numbers ($p$ vectors (columns) of dimension $n$ (lines)).

Here is for example a 3x2 matrix:


     0.2  -0.6
     0.3   1.0
     0.5   3.4
     
In Python, it would be defined by

In [10]:
m = np.array([[0.2, 0.3, 0.5], [-0.6, 1.0, 3.4]])
m


array([[ 0.2,  0.3,  0.5],
       [-0.6,  1. ,  3.4]])

In [11]:
m.shape  # dimensions of the matrix

(2, 3)